// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getABCAnalysis = `-- name: GetABCAnalysis :many
WITH product_values AS (
    SELECT p.id AS product_id, p.name, COALESCE(SUM(pss.sales_revenue), 0)::numeric AS value
    FROM products p
    LEFT JOIN product_sales_summary pss ON pss.product_id = p.id
    WHERE p.business_id = $1
    GROUP BY p.id, p.name
),
ranked AS (
    SELECT product_id, name, value,
           COALESCE(SUM(value) OVER (), 0)::numeric AS total_value,
           COALESCE(SUM(value) OVER (ORDER BY value DESC, name ASC), 0)::numeric AS cumulative_value
    FROM product_values
)
SELECT product_id, name, value, total_value, cumulative_value,
       CASE
           WHEN total_value = 0 THEN 'C'
           WHEN cumulative_value / total_value <= 0.80 THEN 'A'
           WHEN cumulative_value / total_value <= 0.95 THEN 'B'
           ELSE 'C'
       END AS class
FROM ranked
ORDER BY value DESC, name ASC
LIMIT $2 OFFSET $3
`

type GetABCAnalysisParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetABCAnalysisRow struct {
	ProductID       uuid.UUID       `json:"product_id"`
	Name            string          `json:"name"`
	Value           decimal.Decimal `json:"value"`
	TotalValue      decimal.Decimal `json:"total_value"`
	CumulativeValue decimal.Decimal `json:"cumulative_value"`
	Class           string          `json:"class"`
}

func (q *Queries) GetABCAnalysis(ctx context.Context, arg GetABCAnalysisParams) ([]GetABCAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getABCAnalysis, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetABCAnalysisRow{}
	for rows.Next() {
		var i GetABCAnalysisRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Value,
			&i.TotalValue,
			&i.CumulativeValue,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDemandForEOQ = `-- name: GetDemandForEOQ :one
SELECT COALESCE(SUM(quantity), 0)::numeric AS demand
FROM stock_movements
WHERE business_id = $1
  AND variant_id = $2
  AND movement_type = 'OUT_SALE'
  AND created_at >= now() - ($3::int * interval '1 day')
`

type GetDemandForEOQParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	Column3    int32     `json:"column_3"`
}

func (q *Queries) GetDemandForEOQ(ctx context.Context, arg GetDemandForEOQParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getDemandForEOQ, arg.BusinessID, arg.VariantID, arg.Column3)
	var demand decimal.Decimal
	err := row.Scan(&demand)
	return demand, err
}

const getLowStock = `-- name: GetLowStock :many
SELECT pv.id AS variant_id, pv.product_id, pv.sku, pv.name, sl.quantity_on_hand, pv.reorder_point
FROM product_variants pv
JOIN stock_levels sl ON sl.variant_id = pv.id
WHERE pv.business_id = $1
  AND pv.track_inventory = true
  AND sl.quantity_on_hand <= pv.reorder_point
ORDER BY sl.quantity_on_hand ASC
LIMIT $2 OFFSET $3
`

type GetLowStockParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetLowStockRow struct {
	VariantID      uuid.UUID       `json:"variant_id"`
	ProductID      uuid.UUID       `json:"product_id"`
	Sku            string          `json:"sku"`
	Name           string          `json:"name"`
	QuantityOnHand decimal.Decimal `json:"quantity_on_hand"`
	ReorderPoint   decimal.Decimal `json:"reorder_point"`
}

func (q *Queries) GetLowStock(ctx context.Context, arg GetLowStockParams) ([]GetLowStockRow, error) {
	rows, err := q.db.Query(ctx, getLowStock, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLowStockRow{}
	for rows.Next() {
		var i GetLowStockRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.QuantityOnHand,
			&i.ReorderPoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
