// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (business_id, actor_user_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, actor_user_id, action, entity_type, entity_id, metadata, created_at
`

type CreateAuditLogParams struct {
	BusinessID  uuid.NullUUID `json:"business_id"`
	ActorUserID uuid.NullUUID `json:"actor_user_id"`
	Action      string        `json:"action"`
	EntityType  string        `json:"entity_type"`
	EntityID    uuid.NullUUID `json:"entity_id"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.BusinessID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
