// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const addBusinessMember = `-- name: AddBusinessMember :one
INSERT INTO business_members (business_id, user_id, clerk_org_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (business_id, user_id) DO UPDATE SET
    clerk_org_id = EXCLUDED.clerk_org_id,
    role = EXCLUDED.role,
    updated_at = now()
RETURNING id, business_id, user_id, clerk_org_id, role, created_at, updated_at
`

type AddBusinessMemberParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	UserID     uuid.UUID `json:"user_id"`
	ClerkOrgID string    `json:"clerk_org_id"`
	Role       string    `json:"role"`
}

func (q *Queries) AddBusinessMember(ctx context.Context, arg AddBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, addBusinessMember,
		arg.BusinessID,
		arg.UserID,
		arg.ClerkOrgID,
		arg.Role,
	)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.ClerkOrgID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveBusinessesByClerkOrgID = `-- name: ArchiveBusinessesByClerkOrgID :exec
UPDATE businesses
SET status = 'archived',
    updated_at = now()
WHERE businesses.clerk_org_id = $1::text
   OR id IN (
    SELECT business_id
    FROM business_members
    WHERE business_members.clerk_org_id = $1::text
)
`

func (q *Queries) ArchiveBusinessesByClerkOrgID(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, archiveBusinessesByClerkOrgID, dollar_1)
	return err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
    clerk_org_id, name, slug, description, business_type, phone, whatsapp, email, website,
    logo_url, cover_image_url, status, address, neighborhood, city, state,
    country, postal_code, latitude, longitude, pickup_available, delivery_available
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
)
RETURNING id, name, slug, description, business_type, phone, whatsapp, email, website, logo_url, cover_image_url, status, address, neighborhood, city, state, country, postal_code, latitude, longitude, pickup_available, delivery_available, created_at, updated_at, clerk_org_id
`

type CreateBusinessParams struct {
	ClerkOrgID        sql.NullString      `json:"clerk_org_id"`
	Name              string              `json:"name"`
	Slug              string              `json:"slug"`
	Description       string              `json:"description"`
	BusinessType      string              `json:"business_type"`
	Phone             sql.NullString      `json:"phone"`
	Whatsapp          sql.NullString      `json:"whatsapp"`
	Email             sql.NullString      `json:"email"`
	Website           sql.NullString      `json:"website"`
	LogoUrl           sql.NullString      `json:"logo_url"`
	CoverImageUrl     sql.NullString      `json:"cover_image_url"`
	Status            string              `json:"status"`
	Address           sql.NullString      `json:"address"`
	Neighborhood      sql.NullString      `json:"neighborhood"`
	City              string              `json:"city"`
	State             string              `json:"state"`
	Country           string              `json:"country"`
	PostalCode        sql.NullString      `json:"postal_code"`
	Latitude          decimal.NullDecimal `json:"latitude"`
	Longitude         decimal.NullDecimal `json:"longitude"`
	PickupAvailable   bool                `json:"pickup_available"`
	DeliveryAvailable bool                `json:"delivery_available"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.ClerkOrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.BusinessType,
		arg.Phone,
		arg.Whatsapp,
		arg.Email,
		arg.Website,
		arg.LogoUrl,
		arg.CoverImageUrl,
		arg.Status,
		arg.Address,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.Country,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.PickupAvailable,
		arg.DeliveryAvailable,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BusinessType,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.Status,
		&i.Address,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.PickupAvailable,
		&i.DeliveryAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const deleteBusinessMemberByClerkOrgAndUser = `-- name: DeleteBusinessMemberByClerkOrgAndUser :exec
DELETE FROM business_members
WHERE clerk_org_id = $1 AND user_id = $2
`

type DeleteBusinessMemberByClerkOrgAndUserParams struct {
	ClerkOrgID string    `json:"clerk_org_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBusinessMemberByClerkOrgAndUser(ctx context.Context, arg DeleteBusinessMemberByClerkOrgAndUserParams) error {
	_, err := q.db.Exec(ctx, deleteBusinessMemberByClerkOrgAndUser, arg.ClerkOrgID, arg.UserID)
	return err
}

const getBusinessForMember = `-- name: GetBusinessForMember :one
SELECT b.id, b.name, b.slug, b.description, b.business_type, b.phone, b.whatsapp, b.email, b.website, b.logo_url, b.cover_image_url, b.status, b.address, b.neighborhood, b.city, b.state, b.country, b.postal_code, b.latitude, b.longitude, b.pickup_available, b.delivery_available, b.created_at, b.updated_at, b.clerk_org_id
FROM businesses b
JOIN business_members bm ON bm.business_id = b.id
WHERE b.id = $1 AND bm.user_id = $2
`

type GetBusinessForMemberParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBusinessForMember(ctx context.Context, arg GetBusinessForMemberParams) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessForMember, arg.ID, arg.UserID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BusinessType,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.Status,
		&i.Address,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.PickupAvailable,
		&i.DeliveryAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}

const getBusinessIDByClerkOrgID = `-- name: GetBusinessIDByClerkOrgID :one
SELECT id
FROM businesses
WHERE businesses.clerk_org_id = $1::text
UNION
SELECT business_id
FROM business_members
WHERE business_members.clerk_org_id = $1::text
LIMIT 1
`

func (q *Queries) GetBusinessIDByClerkOrgID(ctx context.Context, dollar_1 string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBusinessIDByClerkOrgID, dollar_1)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBusinessMemberRole = `-- name: GetBusinessMemberRole :one
SELECT role
FROM business_members
WHERE business_id = $1 AND user_id = $2 AND clerk_org_id = $3
`

type GetBusinessMemberRoleParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	UserID     uuid.UUID `json:"user_id"`
	ClerkOrgID string    `json:"clerk_org_id"`
}

func (q *Queries) GetBusinessMemberRole(ctx context.Context, arg GetBusinessMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getBusinessMemberRole, arg.BusinessID, arg.UserID, arg.ClerkOrgID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getPublicBusinessBySlug = `-- name: GetPublicBusinessBySlug :one
SELECT id, name, slug, description, business_type, phone, whatsapp, email, website,
       logo_url, cover_image_url, address, neighborhood, city, state, country,
       postal_code, latitude, longitude, pickup_available, delivery_available
FROM businesses
WHERE slug = $1 AND status = 'active'
`

type GetPublicBusinessBySlugRow struct {
	ID                uuid.UUID           `json:"id"`
	Name              string              `json:"name"`
	Slug              string              `json:"slug"`
	Description       string              `json:"description"`
	BusinessType      string              `json:"business_type"`
	Phone             sql.NullString      `json:"phone"`
	Whatsapp          sql.NullString      `json:"whatsapp"`
	Email             sql.NullString      `json:"email"`
	Website           sql.NullString      `json:"website"`
	LogoUrl           sql.NullString      `json:"logo_url"`
	CoverImageUrl     sql.NullString      `json:"cover_image_url"`
	Address           sql.NullString      `json:"address"`
	Neighborhood      sql.NullString      `json:"neighborhood"`
	City              string              `json:"city"`
	State             string              `json:"state"`
	Country           string              `json:"country"`
	PostalCode        sql.NullString      `json:"postal_code"`
	Latitude          decimal.NullDecimal `json:"latitude"`
	Longitude         decimal.NullDecimal `json:"longitude"`
	PickupAvailable   bool                `json:"pickup_available"`
	DeliveryAvailable bool                `json:"delivery_available"`
}

func (q *Queries) GetPublicBusinessBySlug(ctx context.Context, slug string) (GetPublicBusinessBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicBusinessBySlug, slug)
	var i GetPublicBusinessBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BusinessType,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.Address,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.PickupAvailable,
		&i.DeliveryAvailable,
	)
	return i, err
}

const listPublicBusinesses = `-- name: ListPublicBusinesses :many
SELECT id, name, slug, description, business_type, logo_url, cover_image_url,
       city, state, country, latitude, longitude, pickup_available, delivery_available
FROM businesses
WHERE status = 'active'
  AND ($1::text IS NULL OR city = $1::text)
  AND ($2::numeric IS NULL OR latitude >= $2::numeric)
  AND ($3::numeric IS NULL OR latitude <= $3::numeric)
  AND ($4::numeric IS NULL OR longitude >= $4::numeric)
  AND ($5::numeric IS NULL OR longitude <= $5::numeric)
ORDER BY name ASC
LIMIT $7 OFFSET $6
`

type ListPublicBusinessesParams struct {
	City        sql.NullString      `json:"city"`
	MinLat      decimal.NullDecimal `json:"min_lat"`
	MaxLat      decimal.NullDecimal `json:"max_lat"`
	MinLng      decimal.NullDecimal `json:"min_lng"`
	MaxLng      decimal.NullDecimal `json:"max_lng"`
	OffsetCount int32               `json:"offset_count"`
	LimitCount  int32               `json:"limit_count"`
}

type ListPublicBusinessesRow struct {
	ID                uuid.UUID           `json:"id"`
	Name              string              `json:"name"`
	Slug              string              `json:"slug"`
	Description       string              `json:"description"`
	BusinessType      string              `json:"business_type"`
	LogoUrl           sql.NullString      `json:"logo_url"`
	CoverImageUrl     sql.NullString      `json:"cover_image_url"`
	City              string              `json:"city"`
	State             string              `json:"state"`
	Country           string              `json:"country"`
	Latitude          decimal.NullDecimal `json:"latitude"`
	Longitude         decimal.NullDecimal `json:"longitude"`
	PickupAvailable   bool                `json:"pickup_available"`
	DeliveryAvailable bool                `json:"delivery_available"`
}

func (q *Queries) ListPublicBusinesses(ctx context.Context, arg ListPublicBusinessesParams) ([]ListPublicBusinessesRow, error) {
	rows, err := q.db.Query(ctx, listPublicBusinesses,
		arg.City,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLng,
		arg.MaxLng,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicBusinessesRow{}
	for rows.Next() {
		var i ListPublicBusinessesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.BusinessType,
			&i.LogoUrl,
			&i.CoverImageUrl,
			&i.City,
			&i.State,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PickupAvailable,
			&i.DeliveryAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses SET
    name = $3,
    description = $4,
    business_type = $5,
    phone = $6,
    whatsapp = $7,
    email = $8,
    website = $9,
    logo_url = $10,
    cover_image_url = $11,
    status = $12,
    address = $13,
    neighborhood = $14,
    city = $15,
    state = $16,
    country = $17,
    postal_code = $18,
    latitude = $19,
    longitude = $20,
    pickup_available = $21,
    delivery_available = $22,
    updated_at = now()
WHERE businesses.id = $1 AND EXISTS (
    SELECT 1 FROM business_members bm
    WHERE bm.business_id = businesses.id
      AND bm.user_id = $2
      AND bm.role IN ('owner', 'manager')
)
RETURNING id, name, slug, description, business_type, phone, whatsapp, email, website, logo_url, cover_image_url, status, address, neighborhood, city, state, country, postal_code, latitude, longitude, pickup_available, delivery_available, created_at, updated_at, clerk_org_id
`

type UpdateBusinessParams struct {
	ID                uuid.UUID           `json:"id"`
	UserID            uuid.UUID           `json:"user_id"`
	Name              string              `json:"name"`
	Description       string              `json:"description"`
	BusinessType      string              `json:"business_type"`
	Phone             sql.NullString      `json:"phone"`
	Whatsapp          sql.NullString      `json:"whatsapp"`
	Email             sql.NullString      `json:"email"`
	Website           sql.NullString      `json:"website"`
	LogoUrl           sql.NullString      `json:"logo_url"`
	CoverImageUrl     sql.NullString      `json:"cover_image_url"`
	Status            string              `json:"status"`
	Address           sql.NullString      `json:"address"`
	Neighborhood      sql.NullString      `json:"neighborhood"`
	City              string              `json:"city"`
	State             string              `json:"state"`
	Country           string              `json:"country"`
	PostalCode        sql.NullString      `json:"postal_code"`
	Latitude          decimal.NullDecimal `json:"latitude"`
	Longitude         decimal.NullDecimal `json:"longitude"`
	PickupAvailable   bool                `json:"pickup_available"`
	DeliveryAvailable bool                `json:"delivery_available"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusiness,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.BusinessType,
		arg.Phone,
		arg.Whatsapp,
		arg.Email,
		arg.Website,
		arg.LogoUrl,
		arg.CoverImageUrl,
		arg.Status,
		arg.Address,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.Country,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.PickupAvailable,
		arg.DeliveryAvailable,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.BusinessType,
		&i.Phone,
		&i.Whatsapp,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.CoverImageUrl,
		&i.Status,
		&i.Address,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.PickupAvailable,
		&i.DeliveryAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClerkOrgID,
	)
	return i, err
}
