// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE products SET status = 'archived', updated_at = now()
WHERE id = $1 AND business_id = $2
`

type ArchiveProductParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error {
	_, err := q.db.Exec(ctx, archiveProduct, arg.ID, arg.BusinessID)
	return err
}

const archiveVariant = `-- name: ArchiveVariant :exec
UPDATE product_variants SET status = 'archived', updated_at = now()
WHERE id = $1 AND business_id = $2
`

type ArchiveVariantParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) ArchiveVariant(ctx context.Context, arg ArchiveVariantParams) error {
	_, err := q.db.Exec(ctx, archiveVariant, arg.ID, arg.BusinessID)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
`

type CreateProductParams struct {
	BusinessID  uuid.UUID      `json:"business_id"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	Brand       sql.NullString `json:"brand"`
	Unit        string         `json:"unit"`
	ProductType string         `json:"product_type"`
	IsHandmade  bool           `json:"is_handmade"`
	IsPublic    bool           `json:"is_public"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.BusinessID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Brand,
		arg.Unit,
		arg.ProductType,
		arg.IsHandmade,
		arg.IsPublic,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.Unit,
		&i.ProductType,
		&i.IsHandmade,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (
    product_id, business_id, sku, barcode, internal_code, name, description, price_note, attributes,
    price, cost, currency, track_inventory, public_stock_status, is_public, reorder_point,
    lead_time_days, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at, description, price_note, is_public
`

type CreateVariantParams struct {
	ProductID         uuid.UUID           `json:"product_id"`
	BusinessID        uuid.UUID           `json:"business_id"`
	Sku               string              `json:"sku"`
	Barcode           sql.NullString      `json:"barcode"`
	InternalCode      string              `json:"internal_code"`
	Name              string              `json:"name"`
	Description       sql.NullString      `json:"description"`
	PriceNote         sql.NullString      `json:"price_note"`
	Attributes        []byte              `json:"attributes"`
	Price             decimal.Decimal     `json:"price"`
	Cost              decimal.NullDecimal `json:"cost"`
	Currency          string              `json:"currency"`
	TrackInventory    bool                `json:"track_inventory"`
	PublicStockStatus string              `json:"public_stock_status"`
	IsPublic          bool                `json:"is_public"`
	ReorderPoint      decimal.Decimal     `json:"reorder_point"`
	LeadTimeDays      int32               `json:"lead_time_days"`
	Status            string              `json:"status"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.BusinessID,
		arg.Sku,
		arg.Barcode,
		arg.InternalCode,
		arg.Name,
		arg.Description,
		arg.PriceNote,
		arg.Attributes,
		arg.Price,
		arg.Cost,
		arg.Currency,
		arg.TrackInventory,
		arg.PublicStockStatus,
		arg.IsPublic,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PriceNote,
		&i.IsPublic,
	)
	return i, err
}

const createVariantImage = `-- name: CreateVariantImage :exec
INSERT INTO product_images (variant_id, url, position) VALUES ($1, $2, 0)
`

type CreateVariantImageParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Url       string    `json:"url"`
}

func (q *Queries) CreateVariantImage(ctx context.Context, arg CreateVariantImageParams) error {
	_, err := q.db.Exec(ctx, createVariantImage, arg.VariantID, arg.Url)
	return err
}

const deleteVariantImages = `-- name: DeleteVariantImages :exec
DELETE FROM product_images WHERE variant_id = $1
`

func (q *Queries) DeleteVariantImages(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantImages, variantID)
	return err
}

const getProductForBusiness = `-- name: GetProductForBusiness :one
SELECT id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
FROM products
WHERE id = $1 AND business_id = $2
`

type GetProductForBusinessParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetProductForBusiness(ctx context.Context, arg GetProductForBusinessParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForBusiness, arg.ID, arg.BusinessID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.Unit,
		&i.ProductType,
		&i.IsHandmade,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByBarcode = `-- name: GetVariantByBarcode :one
SELECT pv.id, pv.product_id, pv.business_id, pv.sku, pv.barcode, pv.internal_code, pv.name, pv.attributes, pv.price, pv.cost, pv.currency, pv.track_inventory, pv.public_stock_status, pv.reorder_point, pv.lead_time_days, pv.status, pv.created_at, pv.updated_at, pv.description, pv.price_note, pv.is_public,
       COALESCE(pi.url, '') AS image_url
FROM product_variants pv
LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE variant_id = pv.id
    ORDER BY position ASC, created_at ASC
    LIMIT 1
) pi ON true
WHERE pv.business_id = $1 AND pv.barcode = $2 AND pv.status = 'active'
`

type GetVariantByBarcodeParams struct {
	BusinessID uuid.UUID      `json:"business_id"`
	Barcode    sql.NullString `json:"barcode"`
}

type GetVariantByBarcodeRow struct {
	ProductVariant ProductVariant `json:"product_variant"`
	ImageUrl       string         `json:"image_url"`
}

func (q *Queries) GetVariantByBarcode(ctx context.Context, arg GetVariantByBarcodeParams) (GetVariantByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, getVariantByBarcode, arg.BusinessID, arg.Barcode)
	var i GetVariantByBarcodeRow
	err := row.Scan(
		&i.ProductVariant.ID,
		&i.ProductVariant.ProductID,
		&i.ProductVariant.BusinessID,
		&i.ProductVariant.Sku,
		&i.ProductVariant.Barcode,
		&i.ProductVariant.InternalCode,
		&i.ProductVariant.Name,
		&i.ProductVariant.Attributes,
		&i.ProductVariant.Price,
		&i.ProductVariant.Cost,
		&i.ProductVariant.Currency,
		&i.ProductVariant.TrackInventory,
		&i.ProductVariant.PublicStockStatus,
		&i.ProductVariant.ReorderPoint,
		&i.ProductVariant.LeadTimeDays,
		&i.ProductVariant.Status,
		&i.ProductVariant.CreatedAt,
		&i.ProductVariant.UpdatedAt,
		&i.ProductVariant.Description,
		&i.ProductVariant.PriceNote,
		&i.ProductVariant.IsPublic,
		&i.ImageUrl,
	)
	return i, err
}

const getVariantBySKU = `-- name: GetVariantBySKU :one
SELECT pv.id, pv.product_id, pv.business_id, pv.sku, pv.barcode, pv.internal_code, pv.name, pv.attributes, pv.price, pv.cost, pv.currency, pv.track_inventory, pv.public_stock_status, pv.reorder_point, pv.lead_time_days, pv.status, pv.created_at, pv.updated_at, pv.description, pv.price_note, pv.is_public,
       COALESCE(pi.url, '') AS image_url
FROM product_variants pv
LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE variant_id = pv.id
    ORDER BY position ASC, created_at ASC
    LIMIT 1
) pi ON true
WHERE pv.business_id = $1 AND pv.sku = $2 AND pv.status = 'active'
`

type GetVariantBySKUParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Sku        string    `json:"sku"`
}

type GetVariantBySKURow struct {
	ProductVariant ProductVariant `json:"product_variant"`
	ImageUrl       string         `json:"image_url"`
}

func (q *Queries) GetVariantBySKU(ctx context.Context, arg GetVariantBySKUParams) (GetVariantBySKURow, error) {
	row := q.db.QueryRow(ctx, getVariantBySKU, arg.BusinessID, arg.Sku)
	var i GetVariantBySKURow
	err := row.Scan(
		&i.ProductVariant.ID,
		&i.ProductVariant.ProductID,
		&i.ProductVariant.BusinessID,
		&i.ProductVariant.Sku,
		&i.ProductVariant.Barcode,
		&i.ProductVariant.InternalCode,
		&i.ProductVariant.Name,
		&i.ProductVariant.Attributes,
		&i.ProductVariant.Price,
		&i.ProductVariant.Cost,
		&i.ProductVariant.Currency,
		&i.ProductVariant.TrackInventory,
		&i.ProductVariant.PublicStockStatus,
		&i.ProductVariant.ReorderPoint,
		&i.ProductVariant.LeadTimeDays,
		&i.ProductVariant.Status,
		&i.ProductVariant.CreatedAt,
		&i.ProductVariant.UpdatedAt,
		&i.ProductVariant.Description,
		&i.ProductVariant.PriceNote,
		&i.ProductVariant.IsPublic,
		&i.ImageUrl,
	)
	return i, err
}

const getVariantForBusiness = `-- name: GetVariantForBusiness :one
SELECT pv.id, pv.product_id, pv.business_id, pv.sku, pv.barcode, pv.internal_code, pv.name, pv.attributes, pv.price, pv.cost, pv.currency, pv.track_inventory, pv.public_stock_status, pv.reorder_point, pv.lead_time_days, pv.status, pv.created_at, pv.updated_at, pv.description, pv.price_note, pv.is_public,
       COALESCE(pi.url, '') AS image_url
FROM product_variants pv
LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE variant_id = pv.id
    ORDER BY position ASC, created_at ASC
    LIMIT 1
) pi ON true
WHERE pv.id = $1 AND pv.business_id = $2
`

type GetVariantForBusinessParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

type GetVariantForBusinessRow struct {
	ProductVariant ProductVariant `json:"product_variant"`
	ImageUrl       string         `json:"image_url"`
}

func (q *Queries) GetVariantForBusiness(ctx context.Context, arg GetVariantForBusinessParams) (GetVariantForBusinessRow, error) {
	row := q.db.QueryRow(ctx, getVariantForBusiness, arg.ID, arg.BusinessID)
	var i GetVariantForBusinessRow
	err := row.Scan(
		&i.ProductVariant.ID,
		&i.ProductVariant.ProductID,
		&i.ProductVariant.BusinessID,
		&i.ProductVariant.Sku,
		&i.ProductVariant.Barcode,
		&i.ProductVariant.InternalCode,
		&i.ProductVariant.Name,
		&i.ProductVariant.Attributes,
		&i.ProductVariant.Price,
		&i.ProductVariant.Cost,
		&i.ProductVariant.Currency,
		&i.ProductVariant.TrackInventory,
		&i.ProductVariant.PublicStockStatus,
		&i.ProductVariant.ReorderPoint,
		&i.ProductVariant.LeadTimeDays,
		&i.ProductVariant.Status,
		&i.ProductVariant.CreatedAt,
		&i.ProductVariant.UpdatedAt,
		&i.ProductVariant.Description,
		&i.ProductVariant.PriceNote,
		&i.ProductVariant.IsPublic,
		&i.ImageUrl,
	)
	return i, err
}

const getVariantImage = `-- name: GetVariantImage :one
SELECT COALESCE(
    (SELECT url
     FROM product_images
     WHERE variant_id = $1
     ORDER BY position ASC, created_at ASC
     LIMIT 1),
    ''
)::text AS url
`

// Storefront image. Variants carry at most one today, so writes replace the
// whole set; the scalar subquery keeps the read row-safe (no ErrNoRows).
func (q *Queries) GetVariantImage(ctx context.Context, variantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVariantImage, variantID)
	var url string
	err := row.Scan(&url)
	return url, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.business_id, p.category_id, p.name, p.slug, p.description, p.brand, p.unit, p.product_type, p.is_handmade, p.is_public, p.status, p.created_at, p.updated_at
FROM products p
WHERE p.business_id = $1
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.Unit,
			&i.ProductType,
			&i.IsHandmade,
			&i.IsPublic,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProductsByBusinessSlug = `-- name: ListPublicProductsByBusinessSlug :many
SELECT p.id, p.name, p.slug, p.description, p.brand, p.unit, p.product_type,
       pv.id AS variant_id, pv.sku, pv.name AS variant_name,
       pv.description AS variant_description, pv.price_note, pv.price, pv.currency,
       pv.public_stock_status,
       COALESCE(pi.url, '') AS image_url
FROM businesses b
JOIN products p ON p.business_id = b.id
JOIN product_variants pv ON pv.product_id = p.id
LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE variant_id = pv.id
    ORDER BY position ASC, created_at ASC
    LIMIT 1
) pi ON true
WHERE b.slug = $1
  AND b.status = 'active'
  AND p.is_public = true
  AND p.status = 'active'
  AND pv.is_public = true
  AND pv.status = 'active'
ORDER BY p.name ASC, pv.created_at ASC
LIMIT $2 OFFSET $3
`

type ListPublicProductsByBusinessSlugParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPublicProductsByBusinessSlugRow struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	Description        string          `json:"description"`
	Brand              sql.NullString  `json:"brand"`
	Unit               string          `json:"unit"`
	ProductType        string          `json:"product_type"`
	VariantID          uuid.UUID       `json:"variant_id"`
	Sku                string          `json:"sku"`
	VariantName        string          `json:"variant_name"`
	VariantDescription sql.NullString  `json:"variant_description"`
	PriceNote          sql.NullString  `json:"price_note"`
	Price              decimal.Decimal `json:"price"`
	Currency           string          `json:"currency"`
	PublicStockStatus  string          `json:"public_stock_status"`
	ImageUrl           string          `json:"image_url"`
}

func (q *Queries) ListPublicProductsByBusinessSlug(ctx context.Context, arg ListPublicProductsByBusinessSlugParams) ([]ListPublicProductsByBusinessSlugRow, error) {
	rows, err := q.db.Query(ctx, listPublicProductsByBusinessSlug, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicProductsByBusinessSlugRow{}
	for rows.Next() {
		var i ListPublicProductsByBusinessSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.Unit,
			&i.ProductType,
			&i.VariantID,
			&i.Sku,
			&i.VariantName,
			&i.VariantDescription,
			&i.PriceNote,
			&i.Price,
			&i.Currency,
			&i.PublicStockStatus,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT pv.id, pv.product_id, pv.business_id, pv.sku, pv.barcode, pv.internal_code, pv.name, pv.attributes, pv.price, pv.cost, pv.currency, pv.track_inventory, pv.public_stock_status, pv.reorder_point, pv.lead_time_days, pv.status, pv.created_at, pv.updated_at, pv.description, pv.price_note, pv.is_public,
       COALESCE(pi.url, '') AS image_url
FROM product_variants pv
LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE variant_id = pv.id
    ORDER BY position ASC, created_at ASC
    LIMIT 1
) pi ON true
WHERE pv.product_id = $1 AND pv.business_id = $2
ORDER BY pv.created_at ASC
`

type ListVariantsByProductParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

type ListVariantsByProductRow struct {
	ProductVariant ProductVariant `json:"product_variant"`
	ImageUrl       string         `json:"image_url"`
}

func (q *Queries) ListVariantsByProduct(ctx context.Context, arg ListVariantsByProductParams) ([]ListVariantsByProductRow, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, arg.ProductID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsByProductRow{}
	for rows.Next() {
		var i ListVariantsByProductRow
		if err := rows.Scan(
			&i.ProductVariant.ID,
			&i.ProductVariant.ProductID,
			&i.ProductVariant.BusinessID,
			&i.ProductVariant.Sku,
			&i.ProductVariant.Barcode,
			&i.ProductVariant.InternalCode,
			&i.ProductVariant.Name,
			&i.ProductVariant.Attributes,
			&i.ProductVariant.Price,
			&i.ProductVariant.Cost,
			&i.ProductVariant.Currency,
			&i.ProductVariant.TrackInventory,
			&i.ProductVariant.PublicStockStatus,
			&i.ProductVariant.ReorderPoint,
			&i.ProductVariant.LeadTimeDays,
			&i.ProductVariant.Status,
			&i.ProductVariant.CreatedAt,
			&i.ProductVariant.UpdatedAt,
			&i.ProductVariant.Description,
			&i.ProductVariant.PriceNote,
			&i.ProductVariant.IsPublic,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMarketplaceProducts = `-- name: SearchMarketplaceProducts :many
SELECT b.slug AS business_slug, b.name AS business_name,
       p.id, p.name, p.slug, p.description, p.brand, p.unit, p.product_type,
       pv.id AS variant_id, pv.sku, pv.name AS variant_name,
       pv.description AS variant_description, pv.price_note, pv.price, pv.currency,
       pv.public_stock_status,
       COALESCE(pi.url, '') AS image_url
FROM businesses b
JOIN products p ON p.business_id = b.id
JOIN product_variants pv ON pv.product_id = p.id
LEFT JOIN LATERAL (
    SELECT url
    FROM product_images
    WHERE variant_id = pv.id
    ORDER BY position ASC, created_at ASC
    LIMIT 1
) pi ON true
WHERE b.status = 'active'
  AND p.is_public = true
  AND p.status = 'active'
  AND pv.is_public = true
  AND pv.status = 'active'
  AND ($1::text = '' OR to_tsvector('simple', p.name || ' ' || p.description) @@ plainto_tsquery('simple', $1::text))
  AND (
    (NOT $2::boolean AND NOT $3::boolean)
    OR (
      b.location_mode IN ('fixed', 'hybrid')
      AND (
        ($2::boolean
          AND ($4::numeric IS NULL OR b.latitude >= $4::numeric)
          AND ($5::numeric IS NULL OR b.latitude <= $5::numeric)
          AND ($6::numeric IS NULL OR b.longitude >= $6::numeric)
          AND ($7::numeric IS NULL OR b.longitude <= $7::numeric)
        )
        OR ($3::boolean
          AND ($8::text IS NULL OR lower(b.country) = lower($8::text))
          AND ($9::text IS NULL OR lower(b.state) = lower($9::text))
          AND ($10::text IS NULL OR lower(b.city) = lower($10::text) OR lower(b.neighborhood) = lower($10::text))
          AND ($11::text IS NULL OR lower(b.city) = lower($11::text))
          AND ($12::text IS NULL OR lower(b.neighborhood) = lower($12::text))
          AND ($13::text IS NULL OR b.postal_code = $13::text)
        )
      )
    )
    OR (
      $3::boolean
      AND b.location_mode IN ('mobile', 'hybrid')
      AND EXISTS (
        SELECT 1
        FROM business_service_areas sa
        WHERE sa.business_id = b.id
          AND ($14::text IS NULL OR sa.country_key = $14::text)
          AND ($15::text IS NULL OR sa.state_key = $15::text)
          AND ($16::text IS NULL OR sa.municipality_key IS NULL OR sa.municipality_key = $16::text)
          AND ($17::text IS NULL OR sa.city_key IS NULL OR sa.city_key = $17::text)
          AND ($18::text IS NULL OR sa.neighborhood_key IS NULL OR sa.neighborhood_key = $18::text)
          AND ($19::text IS NULL OR sa.postal_code_key IS NULL OR sa.postal_code_key = $19::text)
      )
    )
  )
ORDER BY p.name ASC
LIMIT $21 OFFSET $20
`

type SearchMarketplaceProductsParams struct {
	SearchQuery     string              `json:"search_query"`
	HasBbox         bool                `json:"has_bbox"`
	HasAreaFilter   bool                `json:"has_area_filter"`
	MinLat          decimal.NullDecimal `json:"min_lat"`
	MaxLat          decimal.NullDecimal `json:"max_lat"`
	MinLng          decimal.NullDecimal `json:"min_lng"`
	MaxLng          decimal.NullDecimal `json:"max_lng"`
	Country         sql.NullString      `json:"country"`
	State           sql.NullString      `json:"state"`
	Municipality    sql.NullString      `json:"municipality"`
	City            sql.NullString      `json:"city"`
	Neighborhood    sql.NullString      `json:"neighborhood"`
	PostalCode      sql.NullString      `json:"postal_code"`
	CountryKey      sql.NullString      `json:"country_key"`
	StateKey        sql.NullString      `json:"state_key"`
	MunicipalityKey sql.NullString      `json:"municipality_key"`
	CityKey         sql.NullString      `json:"city_key"`
	NeighborhoodKey sql.NullString      `json:"neighborhood_key"`
	PostalCodeKey   sql.NullString      `json:"postal_code_key"`
	OffsetCount     int32               `json:"offset_count"`
	LimitCount      int32               `json:"limit_count"`
}

type SearchMarketplaceProductsRow struct {
	BusinessSlug       string          `json:"business_slug"`
	BusinessName       string          `json:"business_name"`
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	Description        string          `json:"description"`
	Brand              sql.NullString  `json:"brand"`
	Unit               string          `json:"unit"`
	ProductType        string          `json:"product_type"`
	VariantID          uuid.UUID       `json:"variant_id"`
	Sku                string          `json:"sku"`
	VariantName        string          `json:"variant_name"`
	VariantDescription sql.NullString  `json:"variant_description"`
	PriceNote          sql.NullString  `json:"price_note"`
	Price              decimal.Decimal `json:"price"`
	Currency           string          `json:"currency"`
	PublicStockStatus  string          `json:"public_stock_status"`
	ImageUrl           string          `json:"image_url"`
}

func (q *Queries) SearchMarketplaceProducts(ctx context.Context, arg SearchMarketplaceProductsParams) ([]SearchMarketplaceProductsRow, error) {
	rows, err := q.db.Query(ctx, searchMarketplaceProducts,
		arg.SearchQuery,
		arg.HasBbox,
		arg.HasAreaFilter,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLng,
		arg.MaxLng,
		arg.Country,
		arg.State,
		arg.Municipality,
		arg.City,
		arg.Neighborhood,
		arg.PostalCode,
		arg.CountryKey,
		arg.StateKey,
		arg.MunicipalityKey,
		arg.CityKey,
		arg.NeighborhoodKey,
		arg.PostalCodeKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMarketplaceProductsRow{}
	for rows.Next() {
		var i SearchMarketplaceProductsRow
		if err := rows.Scan(
			&i.BusinessSlug,
			&i.BusinessName,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.Unit,
			&i.ProductType,
			&i.VariantID,
			&i.Sku,
			&i.VariantName,
			&i.VariantDescription,
			&i.PriceNote,
			&i.Price,
			&i.Currency,
			&i.PublicStockStatus,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    category_id = $3,
    name = $4,
    description = $5,
    brand = $6,
    unit = $7,
    product_type = $8,
    is_handmade = $9,
    is_public = $10,
    status = $11,
    updated_at = now()
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	BusinessID  uuid.UUID      `json:"business_id"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Brand       sql.NullString `json:"brand"`
	Unit        string         `json:"unit"`
	ProductType string         `json:"product_type"`
	IsHandmade  bool           `json:"is_handmade"`
	IsPublic    bool           `json:"is_public"`
	Status      string         `json:"status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.BusinessID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Unit,
		arg.ProductType,
		arg.IsHandmade,
		arg.IsPublic,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.Unit,
		&i.ProductType,
		&i.IsHandmade,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants SET
    sku = $3,
    barcode = $4,
    internal_code = $5,
    name = $6,
    description = $7,
    price_note = $8,
    attributes = $9,
    price = $10,
    cost = $11,
    currency = $12,
    track_inventory = $13,
    public_stock_status = $14,
    is_public = COALESCE($18::boolean, is_public),
    reorder_point = $15,
    lead_time_days = $16,
    status = $17,
    updated_at = now()
WHERE id = $1 AND business_id = $2
RETURNING id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at, description, price_note, is_public
`

type UpdateVariantParams struct {
	ID                uuid.UUID           `json:"id"`
	BusinessID        uuid.UUID           `json:"business_id"`
	Sku               string              `json:"sku"`
	Barcode           sql.NullString      `json:"barcode"`
	InternalCode      string              `json:"internal_code"`
	Name              string              `json:"name"`
	Description       sql.NullString      `json:"description"`
	PriceNote         sql.NullString      `json:"price_note"`
	Attributes        []byte              `json:"attributes"`
	Price             decimal.Decimal     `json:"price"`
	Cost              decimal.NullDecimal `json:"cost"`
	Currency          string              `json:"currency"`
	TrackInventory    bool                `json:"track_inventory"`
	PublicStockStatus string              `json:"public_stock_status"`
	ReorderPoint      decimal.Decimal     `json:"reorder_point"`
	LeadTimeDays      int32               `json:"lead_time_days"`
	Status            string              `json:"status"`
	IsPublic          pgtype.Bool         `json:"is_public"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.BusinessID,
		arg.Sku,
		arg.Barcode,
		arg.InternalCode,
		arg.Name,
		arg.Description,
		arg.PriceNote,
		arg.Attributes,
		arg.Price,
		arg.Cost,
		arg.Currency,
		arg.TrackInventory,
		arg.PublicStockStatus,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.Status,
		arg.IsPublic,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PriceNote,
		&i.IsPublic,
	)
	return i, err
}
