// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE products SET status = 'archived', updated_at = now()
WHERE id = $1 AND business_id = $2
`

type ArchiveProductParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error {
	_, err := q.db.Exec(ctx, archiveProduct, arg.ID, arg.BusinessID)
	return err
}

const archiveVariant = `-- name: ArchiveVariant :exec
UPDATE product_variants SET status = 'archived', updated_at = now()
WHERE id = $1 AND business_id = $2
`

type ArchiveVariantParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) ArchiveVariant(ctx context.Context, arg ArchiveVariantParams) error {
	_, err := q.db.Exec(ctx, archiveVariant, arg.ID, arg.BusinessID)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
`

type CreateProductParams struct {
	BusinessID  uuid.UUID      `json:"business_id"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	Brand       sql.NullString `json:"brand"`
	Unit        string         `json:"unit"`
	ProductType string         `json:"product_type"`
	IsHandmade  bool           `json:"is_handmade"`
	IsPublic    bool           `json:"is_public"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.BusinessID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Brand,
		arg.Unit,
		arg.ProductType,
		arg.IsHandmade,
		arg.IsPublic,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.Unit,
		&i.ProductType,
		&i.IsHandmade,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (
    product_id, business_id, sku, barcode, internal_code, name, attributes,
    price, cost, currency, track_inventory, public_stock_status, reorder_point,
    lead_time_days, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at
`

type CreateVariantParams struct {
	ProductID         uuid.UUID           `json:"product_id"`
	BusinessID        uuid.UUID           `json:"business_id"`
	Sku               string              `json:"sku"`
	Barcode           sql.NullString      `json:"barcode"`
	InternalCode      string              `json:"internal_code"`
	Name              string              `json:"name"`
	Attributes        []byte              `json:"attributes"`
	Price             decimal.Decimal     `json:"price"`
	Cost              decimal.NullDecimal `json:"cost"`
	Currency          string              `json:"currency"`
	TrackInventory    bool                `json:"track_inventory"`
	PublicStockStatus string              `json:"public_stock_status"`
	ReorderPoint      decimal.Decimal     `json:"reorder_point"`
	LeadTimeDays      int32               `json:"lead_time_days"`
	Status            string              `json:"status"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.BusinessID,
		arg.Sku,
		arg.Barcode,
		arg.InternalCode,
		arg.Name,
		arg.Attributes,
		arg.Price,
		arg.Cost,
		arg.Currency,
		arg.TrackInventory,
		arg.PublicStockStatus,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductForBusiness = `-- name: GetProductForBusiness :one
SELECT id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
FROM products
WHERE id = $1 AND business_id = $2
`

type GetProductForBusinessParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetProductForBusiness(ctx context.Context, arg GetProductForBusinessParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForBusiness, arg.ID, arg.BusinessID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.Unit,
		&i.ProductType,
		&i.IsHandmade,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByBarcode = `-- name: GetVariantByBarcode :one
SELECT id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at
FROM product_variants
WHERE business_id = $1 AND barcode = $2 AND status = 'active'
`

type GetVariantByBarcodeParams struct {
	BusinessID uuid.UUID      `json:"business_id"`
	Barcode    sql.NullString `json:"barcode"`
}

func (q *Queries) GetVariantByBarcode(ctx context.Context, arg GetVariantByBarcodeParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByBarcode, arg.BusinessID, arg.Barcode)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantBySKU = `-- name: GetVariantBySKU :one
SELECT id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at
FROM product_variants
WHERE business_id = $1 AND sku = $2 AND status = 'active'
`

type GetVariantBySKUParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Sku        string    `json:"sku"`
}

func (q *Queries) GetVariantBySKU(ctx context.Context, arg GetVariantBySKUParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantBySKU, arg.BusinessID, arg.Sku)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantForBusiness = `-- name: GetVariantForBusiness :one
SELECT id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at
FROM product_variants
WHERE id = $1 AND business_id = $2
`

type GetVariantForBusinessParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetVariantForBusiness(ctx context.Context, arg GetVariantForBusinessParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantForBusiness, arg.ID, arg.BusinessID)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
FROM products
WHERE business_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.Unit,
			&i.ProductType,
			&i.IsHandmade,
			&i.IsPublic,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProductsByBusinessSlug = `-- name: ListPublicProductsByBusinessSlug :many
SELECT p.id, p.name, p.slug, p.description, p.brand, p.unit, p.product_type,
       pv.id AS variant_id, pv.sku, pv.name AS variant_name, pv.price, pv.currency,
       pv.public_stock_status
FROM businesses b
JOIN products p ON p.business_id = b.id
JOIN product_variants pv ON pv.product_id = p.id
WHERE b.slug = $1
  AND b.status = 'active'
  AND p.is_public = true
  AND p.status = 'active'
  AND pv.status = 'active'
ORDER BY p.name ASC, pv.created_at ASC
LIMIT $2 OFFSET $3
`

type ListPublicProductsByBusinessSlugParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPublicProductsByBusinessSlugRow struct {
	ID                uuid.UUID       `json:"id"`
	Name              string          `json:"name"`
	Slug              string          `json:"slug"`
	Description       string          `json:"description"`
	Brand             sql.NullString  `json:"brand"`
	Unit              string          `json:"unit"`
	ProductType       string          `json:"product_type"`
	VariantID         uuid.UUID       `json:"variant_id"`
	Sku               string          `json:"sku"`
	VariantName       string          `json:"variant_name"`
	Price             decimal.Decimal `json:"price"`
	Currency          string          `json:"currency"`
	PublicStockStatus string          `json:"public_stock_status"`
}

func (q *Queries) ListPublicProductsByBusinessSlug(ctx context.Context, arg ListPublicProductsByBusinessSlugParams) ([]ListPublicProductsByBusinessSlugRow, error) {
	rows, err := q.db.Query(ctx, listPublicProductsByBusinessSlug, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicProductsByBusinessSlugRow{}
	for rows.Next() {
		var i ListPublicProductsByBusinessSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.Unit,
			&i.ProductType,
			&i.VariantID,
			&i.Sku,
			&i.VariantName,
			&i.Price,
			&i.Currency,
			&i.PublicStockStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at
FROM product_variants
WHERE product_id = $1 AND business_id = $2
ORDER BY created_at ASC
`

type ListVariantsByProductParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) ListVariantsByProduct(ctx context.Context, arg ListVariantsByProductParams) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, arg.ProductID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BusinessID,
			&i.Sku,
			&i.Barcode,
			&i.InternalCode,
			&i.Name,
			&i.Attributes,
			&i.Price,
			&i.Cost,
			&i.Currency,
			&i.TrackInventory,
			&i.PublicStockStatus,
			&i.ReorderPoint,
			&i.LeadTimeDays,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMarketplaceProducts = `-- name: SearchMarketplaceProducts :many
SELECT b.slug AS business_slug, b.name AS business_name,
       p.id, p.name, p.slug, p.description, p.brand, p.unit, p.product_type,
       pv.id AS variant_id, pv.sku, pv.name AS variant_name, pv.price, pv.currency,
       pv.public_stock_status
FROM businesses b
JOIN products p ON p.business_id = b.id
JOIN product_variants pv ON pv.product_id = p.id
WHERE b.status = 'active'
  AND p.is_public = true
  AND p.status = 'active'
  AND pv.status = 'active'
  AND ($1::text = '' OR to_tsvector('simple', p.name || ' ' || p.description) @@ plainto_tsquery('simple', $1))
ORDER BY p.name ASC
LIMIT $2 OFFSET $3
`

type SearchMarketplaceProductsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchMarketplaceProductsRow struct {
	BusinessSlug      string          `json:"business_slug"`
	BusinessName      string          `json:"business_name"`
	ID                uuid.UUID       `json:"id"`
	Name              string          `json:"name"`
	Slug              string          `json:"slug"`
	Description       string          `json:"description"`
	Brand             sql.NullString  `json:"brand"`
	Unit              string          `json:"unit"`
	ProductType       string          `json:"product_type"`
	VariantID         uuid.UUID       `json:"variant_id"`
	Sku               string          `json:"sku"`
	VariantName       string          `json:"variant_name"`
	Price             decimal.Decimal `json:"price"`
	Currency          string          `json:"currency"`
	PublicStockStatus string          `json:"public_stock_status"`
}

func (q *Queries) SearchMarketplaceProducts(ctx context.Context, arg SearchMarketplaceProductsParams) ([]SearchMarketplaceProductsRow, error) {
	rows, err := q.db.Query(ctx, searchMarketplaceProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMarketplaceProductsRow{}
	for rows.Next() {
		var i SearchMarketplaceProductsRow
		if err := rows.Scan(
			&i.BusinessSlug,
			&i.BusinessName,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.Unit,
			&i.ProductType,
			&i.VariantID,
			&i.Sku,
			&i.VariantName,
			&i.Price,
			&i.Currency,
			&i.PublicStockStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    category_id = $3,
    name = $4,
    description = $5,
    brand = $6,
    unit = $7,
    product_type = $8,
    is_handmade = $9,
    is_public = $10,
    status = $11,
    updated_at = now()
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, category_id, name, slug, description, brand, unit, product_type, is_handmade, is_public, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	BusinessID  uuid.UUID      `json:"business_id"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Brand       sql.NullString `json:"brand"`
	Unit        string         `json:"unit"`
	ProductType string         `json:"product_type"`
	IsHandmade  bool           `json:"is_handmade"`
	IsPublic    bool           `json:"is_public"`
	Status      string         `json:"status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.BusinessID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Unit,
		arg.ProductType,
		arg.IsHandmade,
		arg.IsPublic,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.Unit,
		&i.ProductType,
		&i.IsHandmade,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants SET
    sku = $3,
    barcode = $4,
    internal_code = $5,
    name = $6,
    attributes = $7,
    price = $8,
    cost = $9,
    currency = $10,
    track_inventory = $11,
    public_stock_status = $12,
    reorder_point = $13,
    lead_time_days = $14,
    status = $15,
    updated_at = now()
WHERE id = $1 AND business_id = $2
RETURNING id, product_id, business_id, sku, barcode, internal_code, name, attributes, price, cost, currency, track_inventory, public_stock_status, reorder_point, lead_time_days, status, created_at, updated_at
`

type UpdateVariantParams struct {
	ID                uuid.UUID           `json:"id"`
	BusinessID        uuid.UUID           `json:"business_id"`
	Sku               string              `json:"sku"`
	Barcode           sql.NullString      `json:"barcode"`
	InternalCode      string              `json:"internal_code"`
	Name              string              `json:"name"`
	Attributes        []byte              `json:"attributes"`
	Price             decimal.Decimal     `json:"price"`
	Cost              decimal.NullDecimal `json:"cost"`
	Currency          string              `json:"currency"`
	TrackInventory    bool                `json:"track_inventory"`
	PublicStockStatus string              `json:"public_stock_status"`
	ReorderPoint      decimal.Decimal     `json:"reorder_point"`
	LeadTimeDays      int32               `json:"lead_time_days"`
	Status            string              `json:"status"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.BusinessID,
		arg.Sku,
		arg.Barcode,
		arg.InternalCode,
		arg.Name,
		arg.Attributes,
		arg.Price,
		arg.Cost,
		arg.Currency,
		arg.TrackInventory,
		arg.PublicStockStatus,
		arg.ReorderPoint,
		arg.LeadTimeDays,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.InternalCode,
		&i.Name,
		&i.Attributes,
		&i.Price,
		&i.Cost,
		&i.Currency,
		&i.TrackInventory,
		&i.PublicStockStatus,
		&i.ReorderPoint,
		&i.LeadTimeDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
