// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const applyStockDelta = `-- name: ApplyStockDelta :one
INSERT INTO stock_levels (business_id, variant_id, location_id, quantity_on_hand)
VALUES ($1, $2, $3, $4)
ON CONFLICT (business_id, variant_id, location_id) DO UPDATE SET
    quantity_on_hand = stock_levels.quantity_on_hand + EXCLUDED.quantity_on_hand,
    updated_at = now()
RETURNING business_id, variant_id, location_id, quantity_on_hand, quantity_reserved, updated_at
`

type ApplyStockDeltaParams struct {
	BusinessID     uuid.UUID       `json:"business_id"`
	VariantID      uuid.UUID       `json:"variant_id"`
	LocationID     uuid.UUID       `json:"location_id"`
	QuantityOnHand decimal.Decimal `json:"quantity_on_hand"`
}

func (q *Queries) ApplyStockDelta(ctx context.Context, arg ApplyStockDeltaParams) (StockLevel, error) {
	row := q.db.QueryRow(ctx, applyStockDelta,
		arg.BusinessID,
		arg.VariantID,
		arg.LocationID,
		arg.QuantityOnHand,
	)
	var i StockLevel
	err := row.Scan(
		&i.BusinessID,
		&i.VariantID,
		&i.LocationID,
		&i.QuantityOnHand,
		&i.QuantityReserved,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventoryLocation = `-- name: CreateInventoryLocation :one
INSERT INTO inventory_locations (business_id, name, is_default)
VALUES ($1, $2, $3)
RETURNING id, business_id, name, is_default, created_at
`

type CreateInventoryLocationParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Name       string    `json:"name"`
	IsDefault  bool      `json:"is_default"`
}

func (q *Queries) CreateInventoryLocation(ctx context.Context, arg CreateInventoryLocationParams) (InventoryLocation, error) {
	row := q.db.QueryRow(ctx, createInventoryLocation, arg.BusinessID, arg.Name, arg.IsDefault)
	var i InventoryLocation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
    business_id, variant_id, location_id, movement_type, quantity, unit_cost,
    reference_type, reference_id, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, business_id, variant_id, location_id, movement_type, quantity, unit_cost, reference_type, reference_id, notes, created_by, created_at
`

type CreateStockMovementParams struct {
	BusinessID    uuid.UUID           `json:"business_id"`
	VariantID     uuid.UUID           `json:"variant_id"`
	LocationID    uuid.UUID           `json:"location_id"`
	MovementType  string              `json:"movement_type"`
	Quantity      decimal.Decimal     `json:"quantity"`
	UnitCost      decimal.NullDecimal `json:"unit_cost"`
	ReferenceType sql.NullString      `json:"reference_type"`
	ReferenceID   sql.NullString      `json:"reference_id"`
	Notes         string              `json:"notes"`
	CreatedBy     uuid.NullUUID       `json:"created_by"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.BusinessID,
		arg.VariantID,
		arg.LocationID,
		arg.MovementType,
		arg.Quantity,
		arg.UnitCost,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VariantID,
		&i.LocationID,
		&i.MovementType,
		&i.Quantity,
		&i.UnitCost,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultInventoryLocation = `-- name: GetDefaultInventoryLocation :one
SELECT id, business_id, name, is_default, created_at
FROM inventory_locations
WHERE business_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultInventoryLocation(ctx context.Context, businessID uuid.UUID) (InventoryLocation, error) {
	row := q.db.QueryRow(ctx, getDefaultInventoryLocation, businessID)
	var i InventoryLocation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listStockLevels = `-- name: ListStockLevels :many
SELECT sl.business_id, sl.variant_id, sl.location_id, sl.quantity_on_hand, sl.quantity_reserved, sl.updated_at
FROM stock_levels sl
WHERE sl.business_id = $1
ORDER BY sl.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListStockLevelsParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListStockLevels(ctx context.Context, arg ListStockLevelsParams) ([]StockLevel, error) {
	rows, err := q.db.Query(ctx, listStockLevels, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockLevel{}
	for rows.Next() {
		var i StockLevel
		if err := rows.Scan(
			&i.BusinessID,
			&i.VariantID,
			&i.LocationID,
			&i.QuantityOnHand,
			&i.QuantityReserved,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT id, business_id, variant_id, location_id, movement_type, quantity, unit_cost, reference_type, reference_id, notes, created_by, created_at
FROM stock_movements
WHERE business_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovements, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovement{}
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.VariantID,
			&i.LocationID,
			&i.MovementType,
			&i.Quantity,
			&i.UnitCost,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
