// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support_feedback.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSupportFeedback = `-- name: CreateSupportFeedback :one
INSERT INTO support_feedback (doc_id, locale, verdict, comment, path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateSupportFeedbackParams struct {
	DocID   string         `json:"doc_id"`
	Locale  string         `json:"locale"`
	Verdict string         `json:"verdict"`
	Comment sql.NullString `json:"comment"`
	Path    sql.NullString `json:"path"`
}

func (q *Queries) CreateSupportFeedback(ctx context.Context, arg CreateSupportFeedbackParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSupportFeedback,
		arg.DocID,
		arg.Locale,
		arg.Verdict,
		arg.Comment,
		arg.Path,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
