// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deidentifyUserByClerkID = `-- name: DeidentifyUserByClerkID :exec
UPDATE users
SET email = NULL,
    first_name = NULL,
    last_name = NULL,
    image_url = NULL,
    updated_at = now()
WHERE clerk_user_id = $1
`

func (q *Queries) DeidentifyUserByClerkID(ctx context.Context, clerkUserID string) error {
	_, err := q.db.Exec(ctx, deidentifyUserByClerkID, clerkUserID)
	return err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, first_name, last_name, image_url, created_at, updated_at FROM users WHERE clerk_user_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_user_id, email, first_name, last_name, image_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromClerk = `-- name: UpsertUserFromClerk :one
INSERT INTO users (clerk_user_id, email, first_name, last_name, image_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (clerk_user_id) DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    image_url = EXCLUDED.image_url,
    updated_at = now()
RETURNING id, clerk_user_id, email, first_name, last_name, image_url, created_at, updated_at
`

type UpsertUserFromClerkParams struct {
	ClerkUserID string         `json:"clerk_user_id"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) UpsertUserFromClerk(ctx context.Context, arg UpsertUserFromClerkParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromClerk,
		arg.ClerkUserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.ImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
